---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prometheus-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
